#!/usr/bin/env python
# -*- coding: utf-8 -*-

PATH_ALPHABET = 'TEXTS/IN/RESOURCES/CHARACTERS/'
PATH_DICTIONARIES = 'TEXTS/IN/RESOURCES/WORDS/'

PATH_BOOKS = 'TEXTS/IN/BOOKS/'
PATH_ARTICLES = 'TEXTS/IN/ARTICLES/'

PATH_DH = 'TEXTS/IN/POLITICAL/DH/'
PATH_WISHES = 'TEXTS/IN/POLITICAL/WISHES/'

PATH_OUT = 'TEXTS/OUT/'

